### ISSUE TITLE
Looking for code example

### ISSUE THREAD

**Issue by jdriesen** [randolphtellis/vue3-transitions#31]
Hi,

First of all, CONGRATZ with the development of this component(s) ! 
Really great.

While reading your docs, I found some example code.
Please take a look at https://randolphtellis.github.io/vue3-transitions/?path=/docs/entry-exit-animations-fadeinout--group.

Though, I'm missing the definitions of your "addItem" and "removeItem" functions, as well as the definition of the "items" array.

Can you please help me out ? (maybe completing the example code ?)

Thanks in advance for your reply,

Kind regards,
Johnny Driesen - Belgium

**Comment by randolphtellis** [comment]
Hi @jdriesen , thank you for your kind words.
You can find the code in here :
`addItem` - https://github.com/randolphtellis/vue3-transitions/blob/main/src/stories/fade-in-out/fade-in-out.stories.ts#L70
`removeItem` - https://github.com/randolphtellis/vue3-transitions/blob/main/src/stories/fade-in-out/fade-in-out.stories.ts#L74

**Comment by jdriesen** [comment]
Thanks Randolph.

 

Kind regards,

 

Johnny
