### ISSUE TITLE
Is possible entry: top?

### ISSUE THREAD

**Issue by mreduar** [randolphtellis/vue3-transitions#32]
I am looking for a package that has some transition like the one in the image and I think that with your package I could achieve it or at least something similar if I only had an entry from the top.
But reading the examples I realize that only left and right is possible. Could it be possible from top and bottom? 

![CamtasiaStudio_ndx0xis651](https://user-images.githubusercontent.com/22550119/174132990-2e0bcc59-b0b0-4bc1-906b-669b862a394a.gif)

**Comment by 50rayn** [comment]
On NPM there is a module called [vue3-sfc-transitions](https://www.npmjs.com/package/vue3-sfc-transitions) which might help you. It has transition modules _SlideYUpTransition_ and _SlideYDownTransition_.

**Comment by mreduar** [comment]
I had to use something similar
https://github.com/MorevM/vue-transitions
since this library seems to be abandoned
